# Generated by Django 5.2 on 2025-04-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='intensity',
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Moderate'), (4, 'Hard'), (5, 'Advanced')], default=0),
            preserve_default=False,
        ),
    ]
