# Generated by Django 5.2 on 2025-04-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workout_custom_name_alter_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
