# Generated by Django 5.2 on 2025-04-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
