# Generated by Django 5.2 on 2025-04-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_trainerquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Workout', 'verbose_name_plural': 'Workouts'},
        ),
    ]
