# Generated by Django 5.2 on 2025-04-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
    ]
